---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Create Dir to Downlaod Tomcat. 
    file: path=/opt/SP/apps/tomcat state=directory
    
  - name: Install Java 1.8 
    apt: name=default-jdk state=present

  - name: Download Tomcat
    get_url: url=http://apachemirror.wuchna.com/tomcat/tomcat-9/v9.0.31/bin/apache-tomcat-9.0.31.tar.gz  dest=/opt/SP/apps/tomcat.tar.gz mode=0755 

  - name: Extract Tomcat
    command: "tar zxf /opt/SP/apps/tomcat.tar.gz  -C /opt/SP/apps/tomcat --strip-components 1"
    notify: 
    - Restart Tomcat

  - name: Copy bankdata Project War Files
    copy: src=/root/.jenkins/workspace/dev_artifact/bankdata-0.0.1-SNAPSHOT.war dest=/opt/SP/apps/tomcat/webapps/ mode=0644
  
    

  handlers:
  - name: Restart Tomcat
    shell: "nohup sh /opt/SP/apps/tomcat/bin/catalina.sh start" 
