---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Create Dir to Downlaod Tomcat. 
    file: path=/opt/SP/apps/tomcat state=directory mode=0755
    
  - name: Install Java 1.8 
    apt: name=default-jdk state=present

  - name: Copy bankdata Project War Files
    copy: src=/root/.jenkins/workspace/dev_artifact/bankdata-0.0.1-SNAPSHOT.war dest=/opt/SP/apps/bankdata.war mode=0644
    
  - name: run command
    shell: "java -jar /opt/SP/apps/bankdata.war"
