---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Create Directory. 
    file: path=/opt/SP/apps state=directory mode=0755
    
  - name: Install Java 1.8 
    apt: name=default-jdk state=present
    
  - name: Remove ROOT folder initially
    command: rm -rf /opt/SP/apps/*

  - name: Copy bankdata Project War Files
    copy: src=/root/.jenkins/workspace/dev_artifact/bankdata-0.0.1-SNAPSHOT.war dest=/opt/SP/apps/bankdata.war mode=0644
    
  - name: Copy customerdata Project War Files
    copy: src=/root/.jenkins/workspace/qa_artifact/bankdata-0.0.2-SNAPSHOT.war dest=/opt/SP/apps/customerdata.war mode=0644
    
  - name: run command for 1st microservice
    shell: "nohup java -jar /opt/SP/apps/bankdata.war &"
    
  - name: run command for 2nd microservice
    shell: "nohup java -jar /opt/SP/apps/customerdata.war --httpPort=8081 &"
